language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t aiyappa/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true aiyappa/docker-react npm run test -- --coverage

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-east-1-206301728823"
    bucket_path: "docker"
    on:
        branch: master
        Access key ID: "$AWS_ACCESS_KEY"
        Secret access key: 
            secure: "$AWS_SECRET_KEY"
