language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t aiyappa/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true aiyappa/docker-react npm run test -- --coverage